### ISSUE TITLE
Watermark does't work

### ISSUE THREAD

**Issue by AlinCG** [intelliants/subrion#448]
If you set Text Watermark - photos won't upload and if you set Picture Watermark - watermark is not applied on photos. It works only on thumbnails.
In my opinion Watermark should be applied only on full image and not on thumbnails.

**Comment by 4unkur** [comment]
Has been fixed in #452 #451.
About the missing watermark on full images: https://projects.intelliants.com/intelliants/autos/issues/39

**Comment by AlinCG** [comment]
I applied the fixes but problem still persist. Maybe is only on my system. Images are not uploaded is Text is enabled.

**Comment by vbezruchkin** [comment]
Hi @AlinCG 
I believe it might a case sensitive issue. You can delete phpimageworkshop from your installation and add this one from github
https://github.com/intelliants/subrion/tree/develop/includes/PHPImageWorkshop
Pay attention to the folder name. The issue should be fixed. 
If not, we can recheck this directly on your website.

Thanks for reports.

**Comment by AlinCG** [comment]
Hi Vasily.  I applied the `phpimageworkshop` folder and it works now.  Thanks.

**Comment by vbezruchkin** [comment]
Great! So we consider issue closed :)

**Comment by AlinCG** [comment]
Hi @vbezruchkin  Is there a way to not apply watermark to **Thumbnails**? I need to apply watermark to large images generated only. Thanks.
