### ISSUE TITLE
Comments Plugin 4.1 broken

### ISSUE THREAD

**Issue by CKENT0369** [intelliants/subrion#534]
Found another bug in the comments plugin.
Using Subrion 4.1.5.10 with "paper" template and comments 4.1.0 plugin. If you enable WYSIWYG in comments config and then submit a comment to an article on the front end, it will display an error "Make Sure you have entered a valid comment" and not submit.

If you disable WYSIWYG then the comment will be submitted.

Tried uninstalling and reinstalling comments with cache clear in between and same issue remains. 

Issue is bigger than that if you approve a comment to show on the front end and go back to that page. You get a blank page.

**Comment by Batry** [comment]
Hello @CKENT0369,

Thanks for the report.

Issues have been fixed: 
https://github.com/intelliants/subrion-plugin-comments/commit/edda80a12b25aa94ed152419146a71878375c17b
https://github.com/intelliants/subrion-plugin-comments/commit/f78eaa9a66f957aa60e5a5f9ff66604831911a2c

**Comment by CKENT0369** [comment]
Only fixed the WYSIWYG issue unfortunately, cleared cache, made changes still get a blank front end if there is a comment present.

**Comment by CKENT0369** [comment]
Update: Issue is with the "Recent comments" block that loads. If I disable the block everything works.

**Comment by vbezruchkin** [comment]
@Batry please recheck this report. Thanks!

**Comment by vbezruchkin** [comment]
Hi @CKENT0369 

Please submit a ticket. We would need your FTP details.

Looks like the issue is related to an obsolete version of the core. Triple-tested in the latest core and it worked as expected.

Thanks again for the participation.

**Comment by CKENT0369** [comment]
This is a newly installed version of subrion. If its obsolete version of core then it was downloaded in the latest package.

**Comment by vbezruchkin** [comment]
We use _develop_ branch of our system for tests and it's considered the latest version. Your version is 4.1.5.10 I guess - I believe @Batry 's fix won't work for your installation, so we'd need to make a custom fix on your website directly.

Thanks

**Comment by CKENT0369** [comment]
How do I provide you with ftp details here again?

**Comment by vbezruchkin** [comment]
No, please send them to support@subrion.org or submit a ticket
Ticket system is still preferred way to discuss private issues https://subrion.org/desk/

Thanks
